/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fa0a5101-1360-4145-a27a-af7bb448e548",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MLZepqL31",
    "aws_user_pools_web_client_id": "nkjrfgpu64boskuci7hhuitog",
    "oauth": {}
};


export default awsmobile;
